wanddicke=1.5;
//Außenmaße
hoehe=20;
breite=20-2*2;
laenge=20-2*2;
$fn=50;

difference(){
    minkowski(){
        cube([breite,laenge,hoehe]);
        cylinder(r=2,h=1);
    }
    translate([wanddicke,wanddicke,wanddicke]){
        minkowski(){
            cube([breite-2*wanddicke,laenge-2*wanddicke,hoehe-2*wanddicke]);
            cylinder(r=2,h=1);
        }
    }
}